---
title: 进化的事情-之一
author: 张列弛
date: '2019-05-08'
slug: On-Evolution
---
之前写过三篇关于进化的博文，简要地介绍了进化论的发展历史，现在打算再写一篇关于进化的文章。首先让我犯难的是这篇文章叫什么名字呢？我大概知道自己想写什么内容，但是觉得不好归纳出一个标题来。名不正则言不顺，我不想没有标题就动笔[^1]，但也不想被一个不成熟的标题限制了内容。想起中学的时候看过周作人的一篇文章，叫做《无生老母的信息》，觉得这宽泛的标题好，既可正名，又不会限制可写的内容[^2]。我也想来这么个标题，但是由于“信息”一词在现在这个“信息社会”有了很别致的意思，我不好再用，所以这篇就叫《进化的事情》吧[^3]。   

我小时候听到拉马克的用进废退理论时，觉得很有道理，这想法很符合直觉；后来了解达尔文的自然选择学说，脑子里转了一个弯后，觉得也很有道理，这想法很合逻辑；等到中学在课本上学到木村资生的中性进化论，发现有点看不懂---不是因为不能理解他的思想，而是不能理解这个思想为何重要。那时我很困惑，为何有这么多理论来解释进化现象？它们的关系是啥？到底哪些对哪些不对？这些问题的答案我以前欲知而不可得，也问也不知道从和问起。之前的文章主要是简述了进化论发展的历史，本篇文章会涉及这些各个进化理论的具体内容[^3]，为小时候的自己。

### 什么是进化   

“进化”对应的英文是 "evolution"，意为“展开”，将其理解为“变化”在多数时候都是准确的，因为进化的实质就是生物体变异的产生和在世代间保存。一个常见的问题是进化有没有方向？现在很多人会不假思索地回答“没有”。不过我觉得，这个问题值得再多想想。严格地讲，要回答这个问题需要先明确什么是“方向”？有人提出将生物体复杂度的增加定义为进化的方向，但马上问题就来了，如何定义生物体的“复杂度”？于是又有人提出可以拿一个生物体所含有的细胞类型的数量（不是细胞的数量）来衡量生物体的复杂度：细胞类型越多的生物体越复杂。当然，有很多人不同意这个标准。先别拘泥于这种细节，因为在这里我并不是想选出一个定义进化方向的标准，只是想给出一个例子，看看相较于大而化之地给出一个“没有”的回答，研究人员是如何抽丝剥茧地思考相关问题的。所以，让我们暂且认可用细胞类型的数量来衡量生物体的“复杂度”这个标准吧，继续前进。有了标准，我们就可以提出一个猜想：生物是朝着增加生物体复杂度的方向进化的。这个猜想对吗？这需要验证。很容易看到，不对，因为有很多生物越变细胞类型越少，就是所谓“退化”，生物体的复杂度在降低。在逻辑上，一个反例就可以证伪一个猜想了。不过生物学不是逻辑学，想要找出一个不含反例生物学命题几乎不可能。让我们稍微放宽标准，将猜想改变一下：大多数生物是朝着生物体复杂度增加的方向进化的。这个猜想对吗？这就不那么容易回答了。这个猜想是否正确需要大量的观察和实验来回答，随口说的意见并没有太大的价值。生物进化的前提是该生物体首先得活下来，所以这个猜想也可以换一个方式表述：在一定环境下，生物复杂度的增加有利于提高生物体的生存能力。这个猜想对不对？有没有一个最佳平衡点，使得生物体的复杂度增加或者降低都不利于生物体生存？这些都是我比较感兴趣，也是可能通过实验来回答的问题。   

进化是事实还是理论？这是另一个有意思的问题。很多人不能分清事实和理论的区别，我想这是一大类关于进化的争论起始的原因。进化是事实，不是理论。我们在野外观察到了生物的变化的产生和保存，我们在实验室里也可以对一些生物实行人工进化（所谓 artificial evolution），所以生物会进化，这是事实，不是理论。那什么是理论呢？拉马克主义是关于进化的理论，达尔文的自然选择学说是关于进化的理论，木村资生学派的（近）中性进化论也是关于进化的理论。由于进化论教育严重倾向于达尔文的学说（至少是在中国的中学教育里），以至于很多人几乎将进化论与自然选择学说等同了，这是不对的。而这些学说也可以分为两部分：事实基础和理论模型。这些学说得以提出所依赖的实际观察是事实，比如人们观察到了细菌可以在和噬箘体的斗争中获得免疫能力，并将其遗传给后代，这是符合拉马克理论的事实（虽然拉马克本人不是根据这个事实提出他的理论的，而是以别的观察为基础；他对观察的诠释对不对也是问题---不是所有理论都有坚实的事实基础的）；适应环境的生物更有机会活下来，这一自然选择理论的基础是符合逻辑的，在生活中也常被观察到；发生在分子水平的基因突变也有大量观察作为支撑，这是中性进化的理论提出的事实基础。那它们的理论部分是什么呢？这些学说是否能够解释，或者，在多大程度上能够解释地球上生物的进化史，这是理论部分，也正是难以下定论的部分。

### 拉马克  

拉马克被认为是第一个系统地提出一个关于进化的理论的人，我也认同这个说法。拉马克的进化大体包括两个部分：1，用进废退；2，获得性遗传。第一个部分试图解释生物体是如何产生变异的，第二个部分则试图解释这些变异是如何传递给后代的。稍微思考一下就可以发现，拉马克的进化理论里蕴含了“适者生存”的意思，因为只有（适应环境）活下来的个体才可以一代一代地将变异遗传下去，越积越多。不过拉马克把重点放在了变异是如何产生和保存上，对选择的过程并不强调而已，这也是他和达尔文最大的区别。那拉马克是对还是错呢？这个问题也不是可以简单的用“对”或“不对”来回答的。拉马克希望用他的进化理论解释多数生物的进化，就这个初心而言，他是错的。现在分子生物学和遗传学的研究进展并不支持他---他关于变异的产生和保存的机制不适用于大多数生物。但我们不能就此苛责他，因为他出生的太早了，这些学科在他去世后很多年才发展起来。同时，拉马克提出的进化机制是有其合理成分的，表观遗传学和细菌的获得性免疫机制方面的研究进展给了拉马克的理论重获新生的机会，我在之前的文章里提过这方面的进展，这里就不赘述了。从这个角度看，拉马克的理论又是正确的，不过是以他自己都没有预料到的方式。拉马克是进化研究的先驱，我希望人们可以更合理的评价他的工作，而不是把他当成衬托达尔文的伟大的背景，因为接下来你会看到达尔文本人就是个“拉马克主义者”。  

### 达尔文  

达尔文的自然选择学说可能是进化理论里最被人熟知的，不过达尔文版的自然选择学说的全貌并不为人熟知。我之前提到达尔文本人就是个“拉马克主义者”，这并不是耸人听闻，想搞个大新闻的说法。二十世纪初人们对达尔文的自然选择学说有个著名的批评，说它 "may explain the survial of the fittest, but cannot explain the arrival of the fittest." 这个批评是犀利的，自然选择不能解释生物体变异是如何产生的[^5]。达尔文是不在乎 "the arrival of the fittest" 吗？不全是。达尔文没有在变异是如何产生这个问题上下大工夫，因为他认可拉马克用进废退的理论，觉得这解释了变异的产生的机制。不过跟拉马克不同的一点是，达尔文认为由于生物群体里个体数量大，所以各种各样的变异已然存在于群体里了，进化并不依赖于新的变异产生；反而是环境变化将适合生存的个体筛选出来是进化的重要过程。前文提到，进化的实质是变异的保存和遗传，而达尔文在这两个过程之间加入了一个筛选的步骤，这是一个天才的创见。根据这个思想提出的进化算法在工程领域的贡献我想会越来越受到人们重视，成为选择学说在进化论外的另一大用武之地；在哺乳动物的获得性免疫系统里和神经发育的过程中，选择理论也在起着塑性的作用，这些话题或许以后会涉及。除了变异的产生和筛选，剩下的就是变异的遗传了，那达尔文有没有考虑这个问题呢？细心如达尔文，自然不会遗漏这么重要的点。可惜，达尔文所认可的是“混合遗传”的理论。什么是混合遗传？就是平均化。红花和白花杂交生个粉红花，这就是对混合遗传最形象的叙述了。但是，混合遗传理论其实是达尔文最大的敌人，因为进化需要将特殊的个体筛选出来，而混合遗传则是倾向于将群体里的个体特征平均化，抹掉稍微有点棱角的个体。所以混合遗传理论对达尔文自然选择学说是极不友好的。怎么办？聪明如达尔文，自然不会坐以待毙。他想出了一个叫做 ["pangenesis"](https://en.wikipedia.org/wiki/Pangenesis#De_Vries) 的学说来解决这个矛盾。在这个理论里，人们可以看到达尔文和拉马克的完美合体。   

达尔文认为生物的形态变异是连续的，形态的进化过程是渐进的。他关于形态连续变异的观点在同时期有人赞同，也有人反对，反对者里就有高尔顿，他认为生物的形态变异是离散的。而关于进化是渐进的观点，也有人反对，比如突变学派的 de Vris 和 Thomas Morgan 等人。前文没有提突变派，绝不是因为它不重要，相反，我认为进化的突变论是在其被提出时最具有科学基础的，因为突变论的发展是紧紧地跟当时最新的孟德尔遗传理论齐头并进的。突变论的提倡者 de Vris 本人就是独立重新发现孟德尔遗传学说的三人之一，并且他亲自做实验，观察到了植物的突变现象；Morgan 则是遗传连锁定律的发现者，他领导了对果蝇突变体的研究，推动了人们对生物遗传和变异理论的理解。七十年代出了一个名叫“间断平衡理论”的进化模型，其提倡者根据这个理论也提出生物进化是跃进式的，不过道金斯，本尼特等人对该理论颇有微词。我在后文还会说到这个理论。变异是连续的还是离散的，进化是渐进的还是跃进的，这些细节对于讨论进化的机制极为重要，所以希望对进化现象感兴趣的朋友将它们记住，虽然现在不一定能理解它们的重要性。   

自然选择理论的发展也不是一直顺风顺水。在二十世纪的早期，自然选择理论曾经历过一段低迷，因为新拉马克理论短暂的复兴和突变论的异军崛起。不过，自然选择理论先是装备上数学武器，然后迅速整合了孟德尔遗传学说（解决了变异如何遗传），遗传因子突变论（解决了变异如何产生），和遗传漂变理论（考虑了随机因素），以新达尔文主义的姿态再度重出江湖，所向披靡，人称“综合进化论”。

未完待续。

[^1]:也不一定每次都是有标题再写的，这是这次不想没标题而已。
[^2]:周作人还有一篇叫《金鱼》的文章，在开头讨论了下文章题目的起法，也很有意思。
[^3]:写了一会儿，发现文章可能会有点长，拆分开比较好，所以在标题里加了个“之一”。
[^4]:有的内容可能在之前的文章里简短地提过，不过如果不是太麻烦，我不会刻意回避这些提过的内容。这里没有提进化的突变论，因为我潜意识里是按照小时候想了解的问题来写的，当年我还不知道进化的突变论。写到后边才发现把这个重要的理论给忽略了，暂时也不打算将它加进来了，不过还后文会介绍。
[^5]:之后我们会看到，达尔文专注于他具有信心的选择过程，不对变异产生和遗传过程大加强调对他的进化理论的发展是极为有益的，给后续新达尔文主义整合其他学派留了空间。
